spring:
  application:
    name: "Spring Boot ChatBot"
  ai:
    openai:
      api-key: ${GROQ_API_KEY}
      base-url: "https://api.groq.com/openai"
      chat:
        options:
          model: "llama-3.1-8b-instant"
          temperature: "0.7"